- name: Deploy GNOME Shell settings
  hosts: localhost
  tasks:
    - name: GNOME Shell settings
      import_role:
        name: gnome-shell

    - name: GNOME Shell extensions
      import_role:
        name: gnome-shell-extensions

- name: Deploy additional apps
  hosts: localhost
  tasks:
    - name: GNOME additional apps
      import_role:
        name: gnome-apps

    - name: Deploy other apps
      import_role:
        name: apps-other
