- name: Install Vitals extension
  include_tasks: extension.yml
  vars:
    uuid: "Vitals@CoreCoding.com"

- name: Install GSConnect
  include_tasks: extension.yml
  vars:
    uuid: "gsconnect@andyholmes.github.io"

- name: Install PaperWM extension
  include_tasks: extension.yml
  vars:
    uuid: "paperwm@paperwm.github.com"

- name: Configure PaperWM extension
  include_tasks: paperwm_config.yml
